/**
 * An In memory list of predefined horoscopes.
 * This is used to generate a consistent daily horoscope for a given zodiac sign.
 */
const horoscopes = [
  "Today is a good day to take risks.",
  "You might encounter a pleasant surprise.",
  "Focus on your relationships today.",
  "An old friend might reconnect.",
  "Challenges may arise, but you’ll conquer them.",
  "Trust your instincts today.",
  "Let go of something that’s holding you back.",
  "Your creativity is at its peak.",
  "You may receive unexpected news.",
  "Stay calm in the face of confusion.",
  "A fresh perspective will help solve a problem.",
  "Kindness will come back to you today.",
  "It’s okay to take a step back and recharge.",
  "Today is ideal for starting new habits.",
  "Watch for signs, the universe is guiding you.",
  "Communication is key in your interactions today.",
  "Don’t hesitate to say no.",
  "Your patience will be rewarded.",
  "Someone values your opinion more than you know.",
  "A financial opportunity may present itself.",
  "Take time to enjoy small victories.",
  "Let your emotions guide your choices today.",
  "Be open to learning something new.",
  "Balance is everything right now.",
  "Your courage will inspire someone else.",
  "Avoid overthinking, trust your flow.",
  "You’re more prepared than you realize.",
  "Spend time in nature if you can.",
  "Reconnect with your inner voice.",
  "Let curiosity guide your actions today.",
  "You may receive clarity on a lingering doubt.",
  "Be flexible, plans may shift unexpectedly.",
  "Take the high road in a disagreement.",
  "Your intuition is unusually sharp today.",
  "Start something you’ve been delaying.",
  "Today holds the energy of renewal.",
  "Nurture your creative side.",
  "Don’t rush, good things take time.",
  "Help someone without expecting anything in return.",
  "Reflect before you react.",
  "A surprise message could change your outlook.",
  "Trust the process you're in.",
  "You’ll feel deeply connected to someone today.",
  "Laughter will heal what words cannot.",
  "A decision you make today will echo positively.",
  "Someone from your past has you on their mind.",
  "Your energy is contagious, use it wisely.",
  "Let go of control to make space for magic.",
  "Today, your dreams may feel closer than ever.",
  "Take a break from screens, clarity will follow.",
  "Something small will bring you great joy.",
  "Your honesty will strengthen a bond.",
  "The universe is nudging you forward.",
  "You are your best investment.",
  "Repetition creates mastery, stay consistent.",
  "A door you thought was closed may open again.",
  "You are protected, move with confidence.",
  "Trust that what’s meant for you will find you.",
  "Celebrate how far you've come.",
  "Small shifts create big results.",
  "Today is a mirror, what you give, you receive.",
  "Don’t be afraid to shine.",
  "Pause before committing to anything long-term.",
  "Be gentle with yourself today.",
  "You have more influence than you realize.",
  "A spark of inspiration is on its way.",
  "Forgiveness will free your heart.",
  "Today may teach you something humbling.",
  "Be mindful of how you speak, words carry power.",
  "An idea you’ve been ignoring deserves attention.",
  "You’ll find beauty in the unexpected.",
  "Listen carefully, someone needs your presence.",
  "Progress, not perfection, is the goal today.",
  "A short journey may have a big impact.",
  "Be ready to adapt, change is your ally.",
  "Release comparison, your path is unique.",
  "Someone sees your potential, even if you don’t.",
  "It’s a good day to say what you mean.",
  "You’ll feel more grounded than usual today.",
  "Kindness from a stranger will uplift you.",
  "A decision made from love is never wrong.",
  "Your boundaries will be tested, stand firm.",
  "Let your heart lead for once.",
  "New insights are forming beneath the surface.",
  "Speak your truth, even if your voice shakes.",
  "You are more aligned than ever before.",
  "What you seek is seeking you.",
  "Momentum is on your side today.",
  "You may get the closure you've been waiting for.",
  "Don't underestimate your own power.",
  "Your actions will speak louder than your words today.",
  "It’s time to plant new seeds for the future.",
  "Today is best spent in reflection.",
  "Let music or art guide you through emotion.",
  "Choose peace over proving a point.",
  "There’s magic in simplicity, slow down.",
  "What felt uncertain now becomes clear.",
  "A new connection may feel strangely familiar.",
  "Release fear, you're exactly where you need to be.",
  "You may uncover a hidden talent today.",
  "Say yes to something spontaneous.",
  "Let the past stay in the past, move forward.",
  "Take credit for your efforts, you’ve earned it.",
  "Today asks you to listen more than you speak.",
  "Make space for something new by clearing the old.",
  "Be open to grace, it’s closer than you think.",
];

export default horoscopes;
